console.log("helloo")
b = new Board()

b.addPiece(b.grid, 0, "yel")
b.addPiece(b.grid, 0, "yel")
b.addPiece(b.grid, 0, "yel")
b.addPiece(b.grid, 0, "red")
b.addPiece(b.grid, 0, "red")
b.addPiece(b.grid, 0, "red")

b.addPiece(b.grid, 1, "red")
b.addPiece(b.grid, 1, "red")
b.addPiece(b.grid, 1, "red")
b.addPiece(b.grid, 1, "yel")
b.addPiece(b.grid, 1, "yel")
b.addPiece(b.grid, 1, "yel")

b.addPiece(b.grid, 2, "yel")
b.addPiece(b.grid, 2, "yel")
b.addPiece(b.grid, 2, "yel")
b.addPiece(b.grid, 2, "red")
b.addPiece(b.grid, 2, "red")
b.addPiece(b.grid, 2, "red")

b.addPiece(b.grid, 3, "red")
b.addPiece(b.grid, 3, "yel")
b.addPiece(b.grid, 3, "red")
b.addPiece(b.grid, 3, "red")
b.addPiece(b.grid, 3, "yel")
b.addPiece(b.grid, 3, "red")

b.addPiece(b.grid, 4, "yel")
b.addPiece(b.grid, 4, "yel")
b.addPiece(b.grid, 4, "red")
b.addPiece(b.grid, 4, "yel")
b.addPiece(b.grid, 4, "red")
b.addPiece(b.grid, 4, "red")

b.addPiece(b.grid, 5, "red")
b.addPiece(b.grid, 5, "red")
b.addPiece(b.grid, 5, "red")
b.addPiece(b.grid, 5, "yel")
b.addPiece(b.grid, 5, "yel")
b.addPiece(b.grid, 5, "yel")

b.addPiece(b.grid, 6, "red")
b.addPiece(b.grid, 6, "yel")
b.addPiece(b.grid, 6, "yel")
b.addPiece(b.grid, 6, "red")
b.addPiece(b.grid, 6, "red")
b.addPiece(b.grid, 6, "red")

c = new Board()
c.addPiece(c.grid, 0, "yel")
c.addPiece(c.grid, 1, "yel")
c.addPiece(c.grid, 4, "yel")
c.addPiece(c.grid, 5, "yel")
c.addPiece(c.grid, 6, "yel")

e = new Board()

